---

- block:
  - name: Create sites root for {{ user.name }}
    file:
      path: "/home/{{ user.name }}/sites"
      state: directory
      owner: "{{ user.name }}"
      group: "{{ user.name }}"

- block:
  - name: Create vhosts for {{ user.name }}
    include: create-vhost.yml
    with_items: "{{ user.vhosts }}"
    loop_control:
      loop_var: vhost
  when: "user.vhosts is defined"

- block:
  - name: Create upstreams for {{ user.name }}
    include: create-vhost.yml upstream=true
    with_items: "{{ user.upstreams }}"
    loop_control:
      loop_var: vhost
  when: "user.upstreams is defined"
