dist: trusty
language: php
php: '7.0'
git:
  depth: 3
  submodules: false
branches:
  only:
    - master
    - develop

addons:
  ssh_known_hosts: 'smirksoftware.com'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - composer install --no-suggest
  - cp .env.example .env
  - php artisan key:generate
  - yarn && yarn run production

before_deploy:
  - openssl aes-256-cbc -K $encrypted_e0f69cba91c5_key -iv $encrypted_e0f69cba91c5_iv -in travis/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - rm .env
  - rm -rf node_modules

deploy:
  provider: script
  skip_cleanup: true
  script: travis/deploy.sh
  on:
    branch: master

