---
# Used only for Debian/Ubuntu installation, as the -t option for apt.
nginx_default_release: ""

# Use the official Nginx PPA for Ubuntu, and the version to use if so.
nginx_ppa_use: false
nginx_ppa_version: stable

# The name of the nginx apt/yum package to install.
nginx_package_name: "nginx"

nginx_worker_processes: "1"
nginx_worker_connections: "1024"
nginx_multi_accept: "off"

# Log files will be placed in the /home/USER/logs/ folder
nginx_error_log_suffix:  "error.log"
nginx_error_log_level: "warn"
nginx_access_log_suffix: "access.log"
nginx_access_log_opts: "main buffer=16k"

nginx_default_error_log: "/var/log/nginx/error.log"
nginx_default_access_log: "/var/log/nginx/access.log"

nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"

nginx_keepalive_timeout: "65"
nginx_keepalive_requests: "100"

nginx_client_max_body_size: "64m"

nginx_server_names_hash_bucket_size: "1024"

nginx_proxy_cache_path: ""

nginx_extra_conf_options: ""
# Example extra main options, used within the main nginx's context:
#   nginx_extra_conf_options: |
#     env VARIABLE;
#     include /etc/nginx/main.d/*.conf;

nginx_extra_http_options: |
    fastcgi_buffers 16 16k;
    fastcgi_buffer_size 32k;

# Example extra http options, printed inside the main server http config:
#    nginx_extra_http_options: |
#      proxy_buffering    off;
#      proxy_set_header   X-Real-IP $remote_addr;
#      proxy_set_header   X-Scheme $scheme;
#      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
#      proxy_set_header   Host $http_host;

nginx_remove_default_vhost: true
nginx_vhosts_filename: "vhosts.conf"
nginx_vhosts: []
# Example vhost below, showing all available options:
# - listen: "80 default_server" # default: "80 default_server"
#   server_name: "example.com" # default: N/A
#   root: "/var/www/example.com" # default: N/A
#   index: "index.html index.htm" # default: "index.html index.htm"
#
#   # Properties that are only added if defined:
#   error_page: ""
#   access_log: ""
#   error_log: ""
#   extra_parameters: "" # Can be used to add extra config blocks (multiline).

nginx_upstreams: []
# - name: myapp1
#   strategy: "ip_hash" # "least_conn", etc.
#   servers: {
#     "srv1.example.com",
#     "srv2.example.com weight=3",
#     "srv3.example.com"
#   }

nginx_ssl_local_path: ssl-certificates
